services:
  - type: web
    name: aricitacts-website-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: EMAIL_USER
        value: "your-email@example.com"
      - key: EMAIL_PASS
        value: "your-email-password"
      - key: API_KEY
        value: "acf30e30e78401e4876d6534e9add756f5060b5c9621d8e9cd183afdddad6655"
